import { NextRequest, NextResponse } from "next/server";
import { createSnowflakeConnection, connectSnowflake } from "@/lib/snowflake";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const connection = createSnowflakeConnection();

  try {
    const body = await req.json();
    const { userId = "user123" } = body;

    await connectSnowflake(connection);

    const rows = await new Promise<any[]>((resolve, reject) => {
      connection.execute({
        sqlText: `
          SELECT USER_ID, QUESTION, AI_RESPONSE, SCORE, PET_MOOD, CREATED_AT
          FROM MY_DB.PUBLIC.STUDY_SESSIONS
          WHERE USER_ID = ?
            AND TOPIC = 'Walk Session'
          ORDER BY CREATED_AT DESC
          LIMIT 10
        `,
        binds: [userId],
        complete: (err, stmt, rows) => {
          if (err) reject(err);
          else resolve(rows ?? []);
        },
      });
    });

    const totalMiles = rows.reduce(
      (sum, row) => sum + Number(row.SCORE || 0),
      0
    );

    const walkCount = rows.length;
    const avgMiles = walkCount > 0 ? totalMiles / walkCount : 0;
    const latestMood = rows[0]?.PET_MOOD || "happy";

    const insight = {
      weeklySummary:
        walkCount === 0
          ? "No walks recorded yet."
          : `You completed ${walkCount} walk(s) and walked about ${totalMiles} mile(s).`,
      fitnessRecommendation:
        avgMiles < 2
          ? "Try to reach 2 miles on your next walk."
          : "Great pace! Try increasing your next walk by 0.5 miles.",
      petMotivationMessage:
        latestMood === "happy"
          ? "Bori is happy and wants another adventure!"
          : "Your puppy misses walking with you. A short walk would help!",
      activityAlert:
        walkCount === 0
          ? "Low activity detected."
          : "Activity data looks good.",
      cortexAvailable: false,
      note: "Snowflake Cortex COMPLETE is not available on this trial account, so this insight was generated by the app fallback logic.",
    };

    return NextResponse.json({
      success: true,
      userId,
      walkCount,
      totalMiles,
      averageMiles: avgMiles,
      walks: rows,
      insight,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    );
  } finally {
    connection.destroy(() => {});
  }
}